# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    categories:
        # Filter name
        label: Categories
        # Model Class name
        modelClass: Baoweb\Articles\Models\Category
        options: getCategoryOptions
        # Filter scope
        scope: filterByCategory

    author:
        # Filter name
        label: Autor
        # Model Class name
        modelClass: Backend\Models\User
        nameFrom: last_name
        # Filter scope
        scope: filterByAuthor

    is_published:
        label: Published
        type: switch
        default: 0
        conditions:
            - is_published <> true
            - is_published = true

    has_no_category:
        label: Nemá kategorii
        type: checkbox
        default: false
        scope: hasNoCategory
