list: $/baoweb/articles/models/category/columns.yaml
modelClass: Baoweb\Articles\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
defaultSort:
    column: internal_name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'baoweb/articles/categories/update/:id'
