list: $/baoweb/articles/controllers/users/columns.yaml
modelClass: Backend\Models\User
title: Assign user rights
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'baoweb/articles/users/update/:id'
defaultSort:
    column: last_name
    direction: asc
