plugin:
    name: 'baoweb.articles::lang.plugin.name'
    description: 'baoweb.articles::lang.plugin.description'
    author: Baoweb
    icon: wn-icon-file-text
    replaces: {  }
permissions:
    create-article:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.createArticle'
    create-article-from-template:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.createArticleFromTemplate'
    delete-articles:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.deleteArticles'
    access-articles:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.accessArticles'
    edit-all-articles:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editAllCategories'
    edit-templates:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editTemplates'
    edit-selected-articles:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editOnlySelectedArticles'
    edit-owned-articles:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editOnlyOwnedArticles'
    edit-categories:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editCategories'
    edit_all_category_fields:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.editAllCategoryFields'
    edit-author:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.edit_author'
    assign-rights:
        tab: 'baoweb.articles::lang.plugin.name'
        label: 'baoweb.articles::lang.permissions.assign_rights'
navigation:
    articles:
        label: 'baoweb.articles::lang.plugin.name'
        url: baoweb/articles/articles
        icon: icon-edit
        permissions:
            - access-articles
        sideMenu:
            articles-side-menu:
                label: 'baoweb.articles::lang.menu.articles'
                url: baoweb/articles/articles
                icon: icon-edit
            templates-side-menu:
                label: 'baoweb.articles::lang.menu.templates'
                url: baoweb/articles/templates
                icon: icon-file
                permissions:
                    - edit-templates
            categories:
                label: 'baoweb.articles::lang.menu.categories'
                url: baoweb/articles/categories
                icon: icon-tags
                permissions:
                    - edit-categories
            user-rights:
                label: 'baoweb.articles::lang.menu.user_rights'
                url: baoweb/articles/users
                icon: icon-users
                permissions:
                    - assign-rights
