list: $/baoweb/articles/models/article/columns.yaml
modelClass: Baoweb\Articles\Models\Article
title: Templates
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'baoweb/articles/templates/update/:id'
