large_text:
    name: Large text
    description: Large block of text
    icon: icon-file-text-o
    fields:
        content:
            label: Text content
            span: full
            type: richeditor
            size: mega

small_text:
    name: Small text
    description: Large block of text
    icon: icon-file-text-o
    fields:
        content:
            label: Text content
            span: full
            type: richeditor
            size: small

gallery:
    name: Gallery
    description: Placeholder for article's gallery
    icon: icon-camera-retro
    fields:
        gallery:
            span: full
            type: partial
            path: ~/plugins/baoweb/articles/config/forms/partials/_gallery_field.htm

documents:
    name: Attached documents
    description: Placeholder for the attached documents
    icon: icon-list
    fields:
        gallery:
            span: full
            type: partial
            path: ~/plugins/baoweb/articles/config/forms/partials/_documents_field.htm

category:
    name: Article list
    description: List of articles from a category
    icon: icon-list
    fields:
        category_listing:
            label: Category
            span: auto
            type: dropdown
        no_of_articles:
            label: Number of articles
            span: auto
            type: number
