large_text:
    name: Large text
    description: Large block of text
    icon: icon-file-text-o
    fields:
        content:
            label: Text content
            span: full
            type: richeditor
            size: mega

small_text:
    name: Small text
    description: Small block of text
    icon: icon-file-text-o
    fields:
        content:
            label: Text content
            span: full
            type: richeditor
            size: small

gallery:
    name: Gallery
    description: Placeholder for article's gallery
    icon: icon-camera-retro
    fields:
        gallery:
            span: full
            type: partial
            path: ~/plugins/baoweb/articles/config/forms/partials/_gallery_field.htm

documents:
    name: Attached documents
    description: Placeholder for the attached documents
    icon: icon-list
    fields:
        gallery:
            span: full
            type: partial
            path: ~/plugins/baoweb/articles/config/forms/partials/_documents_field.htm

category:
    name: Article list
    description: List of articles from a category
    icon: icon-list
    fields:
        box_title:
            label: Nadpis boxu
            span: full
            type: text
        category_listing:
            label: Category
            span: auto
            type: dropdown
        no_of_articles:
            label: Number of articles
            span: auto
            type: number
        compact_list:
            label: Compact list
            type: switch
            default: 0
            span: auto

project_header_2:
    name: Project header - two logos
    description: Project header with two logos
    icon: icon-header
    fields:
        logos:
            label: Loga
            type: section
            span: full
        logo1:
            label: First logo
            type: mediafinder
            imageWidth: 300px
            mode: image
            span: storm
            cssClass: col-md-6
        logo2:
            label: Second logo
            type: mediafinder
            imageWidth: 300px
            mode: image
            span: storm
            cssClass: col-md-6
        link:
            label: Odkazy
            type: section
            span: full
        logo1_link:
            label: First logo link
            type: text
            span: storm
            cssClass: col-md-6
        logo2_link:
            label: Second logo link
            type: text
            span: storm
            cssClass: col-md-6
        text:
            label: Header text
            span: full
            type: richeditor
            size: large

project_header_3:
    name: Project header - three logos
    description: Project header with three logos
    icon: icon-header
    fields:
        logos:
            label: Loga
            type: section
            span: full
        logo1:
            label: First logo
            type: mediafinder
            imageWidth: 300px
            mode: image
            span: storm
            cssClass: col-md-4
        logo2:
            label: Second logo
            type: mediafinder
            imageWidth: 300px
            mode: image
            span: storm
            cssClass: col-md-4
        logo3:
            label: Third logo
            type: mediafinder
            imageWidth: 300px
            mode: image
            span: storm
            cssClass: col-md-4
        link:
            label: Odkazy
            type: section
            span: full
        logo1_link:
            label: First logo link
            type: text
            span: storm
            cssClass: col-md-4
        logo2_link:
            label: Second logo link
            type: text
            span: storm
            cssClass: col-md-4
        logo3_link:
            label: third logo link
            type: text
            span: storm
            cssClass: col-md-4
        header_text:
            label: Header text
            span: full
            type: richeditor
            size: large
